cabal-version:      2.4
name:               chaos
version:            0.1.0.0
build-type:         Simple

library
  hs-source-dirs:   src
  exposed-modules:  Chaos
  build-depends:    base >=4.14 && <5,
                    aeson,
                    text,
                    bytestring,
                    http-conduit,
                    mtl,
                    containers,
                    unordered-containers,
                    vector,
                    split,
                    lens,
                    async,
                    stm,
                    exceptions
  default-language: Haskell2010
