name: Deploy to Deno Deploy
"on":
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: chaos
          entrypoint: main.ts
          import-map: deno.json
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
