name: Deploy to Railway
"on":
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Deploy to Railway
        run: railway up --service chaos
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
